name: Windows.

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'Telegram/build/docker/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/SourceFiles/platform/linux/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.sh'
      - 'Telegram/Telegram.plist'
  workflow_dispatch:
    inputs:
      buildCommit:
        description: 'Commit for building. Default it latest on branch'
        required: false
        type: string
        default: ''

jobs:

  windows:
    name: Windows
    runs-on: aws-windows
    continue-on-error: true

    strategy:
      matrix:
        arch: [x64]

    env:
      UPLOAD_ARTIFACT: "true"
      ONLY_CACHE: "false"
      PREPARE_PATH: "Telegram/build/prepare/prepare.py"
      PreferredToolArchitecture: "x64"

    defaults:
      run:
        shell: cmd

    steps:
      - name: Prepare directories.
        run: |
          mklink /d %GITHUB_WORKSPACE%\TBuild %userprofile%\TBuild
          echo TBUILD=%GITHUB_WORKSPACE%\TBuild>>%GITHUB_ENV%
          mklink /d %userprofile%\TBuild\Libraries %GITHUB_WORKSPACE%\Libraries

      - name: Clone.
        uses: actions/checkout@v3.1.0
        if: github.event.inputs.buildCommit == ''
        with:
          submodules: recursive
          path: ${{ env.TBUILD }}\tdesktop

      - name: Clone with checkout.
        uses: actions/checkout@v3.1.0
        if: github.event.inputs.buildCommit != ''
        with:
          submodules: recursive
          path: ${{ env.TBUILD }}\tdesktop
          ref: ${{ github.event.inputs.buildCommit }}

      - name: Libraries.
        env:
          GYP_MSVS_OVERRIDE_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Community\'
          GYP_MSVS_VERSION: 2022
        run: '%TBUILD%\%REPO_NAME%\Telegram\build\prepare\win.bat silent'

      - name: Read defines.
        shell: bash
        run: |
          DEFINE=""
          if [ -n "${{ matrix.defines }}" ]; then
            DEFINE="-D ${{ matrix.defines }}=ON"
            echo Define from matrix: $DEFINE
            echo "ARTIFACT_NAME=Telegram_${{ matrix.arch }}_${{ matrix.defines }}" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=Telegram_${{ matrix.arch }}" >> $GITHUB_ENV
          fi
          echo "TDESKTOP_BUILD_DEFINE=$DEFINE" >> $GITHUB_ENV

      - name: Telegram Desktop build.
        if: env.ONLY_CACHE == 'false'
        run: |
          cd %TBUILD%\tdesktop\Telegram
          call configure.bat ^
          ${{ matrix.arch }} ^
          -D TDESKTOP_API_TEST=OFF ^
          -D TDESKTOP_API_ID=${{ secrets.API_ID }} ^
          -D TDESKTOP_API_HASH=${{ secrets.API_HASH }} ^
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF ^
          -D DESKTOP_APP_NO_PDB=ON ^
          %TDESKTOP_BUILD_DEFINE% ^
          -DCMAKE_SYSTEM_VERSION=%SDK%
          cd ..\out
          msbuild -m Telegram.sln /p:Configuration=Release,Platform=${{ matrix.arch }}
      - name: Move and hash artifact.
        if: env.UPLOAD_ARTIFACT == 'true'
        run: |
          mkdir artifact
          move %TBUILD%\tdesktop\out\Release\Telegram.exe artifact/Telegram_${{ matrix.arch }}.exe
          certutil -hashfile artifact/Telegram_${{ matrix.arch }}.exe SHA256 | find /i /v "SHA256" | find /i /v "CertUtil" > artifact/Telegram_${{ matrix.arch }}_sha256.txt
      - uses: actions/upload-artifact@master
        name: Upload artifact.
        if: env.UPLOAD_ARTIFACT == 'true'
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifact\
